baseurl: "cede1f748c2d14a50bd089a23ebface0d18b2d5a/"
# title: "Ślub Marii i Michała"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

copyright: Everything is mine (almost)
defaultContentLanguage: en
languages:
  en:
    title: English
    menu:
      main:
        - name: Home
          url: ""
          weight: 1
        - name: Directions
          url: "directions/"
          weight: 2
        - name: About ceremony
          url: "ceremony/"
          weight: 3
        - name: About party
          url: "party/"
          weight: 4
        - name: F.A.Q
          url: "faq/"
          weight: 5
    languageName: English 🇬🇧
    weight: 1
  pl:
    params:
      navigation:
        help: Pomoc
    title: Polski
    menu:
      main:
        - name: Strona główna
          url: "pl"
          weight: 1
        - name: Jak dojechać
          url: "pl/directions/"
          weight: 2
        - name: O Mszy
          url: "pl/ceremony/"
          weight: 3
        - name: O przyjęciu
          url: "pl/party/"
          weight: 4
        - name: Często zadawane pytania
          url: "pl/faq/"
          weight: 5
    languageName: Polski 🇵🇱
    weight: 2
  ru:
    title: Русский
    menu:
      main:
        - name: В начало
          url: "ru"
          weight: 1
        - name: Как добраться 
          url: "ru/directions/"
          weight: 2
        - name: О свадебной церемонии
          url: "ru/ceremony/"
          weight: 3
        - name: Банкет
          url: "ru/party/"
          weight: 4
        - name: Часто задаваемые вопросы 
          url: "ru/faq/"
          weight: 5 
    languageName: Русский 🇷🇺
    weight: 3
params:
  navigation:
    help: Help

params:
  description: "A website dedicated to the wedding of Maria and Michal"
  footer: "Made with [Hugo](https://gohugo.io/) and [hugo-xmin](https://github.com/yihui/hugo-xmin)" 

markup:
  goldmark:
    renderer:
      unsafe: true
