baseurl: "/"
# title: "Michał Siemaszko personal website"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

copyright: Everything is mine (almost)
defaultContentLanguage: en
languages:
  en:
    title: English
    menu:
      main:
        - name: Home
          url: ""
          weight: 1
        - name: Research 
          url: "research/"
          weight: 2
        - name: Contact
          url: "contact/"
          weight: 3
    languageName: English 🇬🇧
    weight: 1
  pl:
    params:
      navigation:
        help: Pomoc
    title: Polski
    menu:
      main:
        - name: Strona główna
          url: "pl"
          weight: 1
        - name: Badania
          url: "pl/research/"
          weight: 2
        - name: Kontakt
          url: "pl/contact/"
          weight: 3
    languageName: Polski 🇵🇱
    weight: 2
params:
  navigation:
    help: Help

params:
  description: "A personal website of Michał Siemaszko"
  footer: "Made with [Hugo](https://gohugo.io/) and [hugo-xmin](https://github.com/yihui/hugo-xmin)" 

markup:
  goldmark:
    renderer:
      unsafe: true
